<?php

/**
 * @file
 * Primary module hooks for Rest Entity Extras module.
 */

use Drupal\Core\Entity\EntityTypeInterface;
use Drupal\Core\Field\BaseFieldDefinition;
use Drupal\Core\Field\FieldStorageDefinitionInterface;

/**
 * Implements hook_entity_base_field_info().
 */
function rest_entity_extras_entity_base_field_info(EntityTypeInterface $entity_type): array
{
  $fields = [];

  // Add computed bids field to Call entity
  if ($entity_type->id() == 'node') {
    $fields['computed_order_calls'] = BaseFieldDefinition::create('entity_reference')
      ->setLabel(t('Related Calls'))
      ->setDescription(t('Calls that reference this order'))
      ->setTargetEntityTypeId('node')
      ->setTargetBundle('bid')
      ->setCardinality(FieldStorageDefinitionInterface::CARDINALITY_UNLIMITED)
      ->setComputed(TRUE)
      ->setClass('\Drupal\rest_entity_extras\Plugin\Field\FieldType\ComputedOrderCallsField')
      ->setDisplayOptions('view', [
        'type' => 'entity_reference_label',
        'weight' => 10,
      ])
      ->setDisplayConfigurable('view', TRUE);

    $fields['computed_call_bids'] = BaseFieldDefinition::create('entity_reference')
      ->setLabel(t('Related Bids'))
      ->setDescription(t('Bids that reference this call'))
      ->setTargetEntityTypeId('node')
      ->setTargetBundle('bid')
      ->setCardinality(FieldStorageDefinitionInterface::CARDINALITY_UNLIMITED)
      ->setComputed(TRUE)
      ->setClass('\Drupal\rest_entity_extras\Plugin\Field\FieldType\ComputedCallBidsField')
      ->setDisplayOptions('view', [
        'type' => 'entity_reference_label',
        'weight' => 10,
      ])
      ->setDisplayConfigurable('view', TRUE);
  }

  return $fields;
}
