name: Build & Deploy Hucha Backend

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0

      - name: Setup PHP with PECL extension
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: grpc, igbinary, memcached

      - name: Validate composer.json
        run: composer validate --no-check-all

      - name: Install composer dependencies
        run: composer install --prefer-dist --no-progress

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_ED25519_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ vars.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Test SSH connection
        run: |
          ssh -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=no ${{ vars.SSH_USERNAME }}@${{ vars.SSH_HOST }} "echo 'Connection successful'"

      - name: Copy rsync-exclude.txt to server
        run: |
          echo "Copying rsync-exclude.txt..."
          scp -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=no $GITHUB_WORKSPACE/rsync-exclude.txt ${{ vars.SSH_USERNAME }}@${{ vars.SSH_HOST }}:/tmp/rsync-exclude.txt
          ssh -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=no ${{ vars.SSH_USERNAME }}@${{ vars.SSH_HOST }} "ls -la /tmp"

      - name: Connect to HuchaCash and Deploy
        id: deploy-drupal
        uses: appleboy/ssh-action@v1.2.0
        env:
          GITHUB_WORKSPACE: ${{ github.workspace }}
        with:
          host: ${{ vars.SSH_HOST }}
          key: ${{ secrets.SSH_ED25519_PRIVATE_KEY }}
          username: ${{ vars.SSH_USERNAME }}
          passphrase: 'kabutindi'
          script: |
            echo "Deploying code to server..."
            rsync -avzq --no-perms --no-owner --no-group \
            --chown=hucha.cash_f48yn987zg5:psacln \
            --exclude-from="/tmp/rsync-exclude.txt" \
            "$GITHUB_WORKSPACE/" "/var/www/vhosts/hucha.cash/web/"

            echo "Rebuilding Drush cache..."
            vendor/drush/drush/drush cr
