name: Build & Deploy Hucha Backend

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0

      - name: Setup PHP with PECL extension
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: grpc

      - name: Validate composer.json
        run: composer validate --no-check-all

      - name: Install composer dependencies
        run: composer install --prefer-dist --no-progress

      - name: Connect to HuchaCash
        id: deploy-drupal
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ vars.SSH_HOST }}
          key: ${{ secrets.SSH_ED25519_PRIVATE_KEY }}
          key_path: ~/.ssh/id_ed25519
          username: ${{ vars.SSH_USERNAME }}
          passphrase: 'kabutindi'
          script: |
            pwd
            ls -la

      - name: Deploy to server
        run: rsync -avzq --no-perms --no-owner --no-group --chown=hucha.cash_f48yn987zg5:psacln -e "ssh -o StrictHostKeyChecking=no -v" --exclude-from="${GITHUB_WORKSPACE}/rsync-exclude.txt" $GITHUB_WORKSPACE/ ${{ vars.SSH_USERNAME }}@${{ vars.SSH_HOST }}:/var/www/vhosts/hucha.cash/web/

      - name: Rebuild drush cache
        run: ssh -o StrictHostKeyChecking=no ${{ vars.SSH_HOST }} "vendor/drush/drush/drush cr"
