name: Build & Deploy

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0

      - name: Validate composer.json
        run: composer validate

      - name: Deploy HuchaCash Core
        id: deploy-drupal
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{secrets.SSH_HOST}}
          key: ${{secrets.SSH_KEY}}
          username: ${{secrets.SSH_USERNAME}}
          passphrase: ''

          script: |
            cd /var/www/vhosts/hucha.cash/
            git fetch --all
            git reset --hard origin/main
            /opt/plesk/php/8.3/bin/php /usr/local/bin/composer install --no-interaction
            vendor/drush/drush/drush updb
            vendor/drush/drush/drush cr
            vendor/drush/drush/drush cim
            vendor/drush/drush/drush updb
            vendor/drush/drush/drush cr
            echo 'HuchaCash deployed successfully!!'
