name: Build & Deploy Hucha Backend

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0

      - name: Debug GITHUB_WORKSPACE
        run: |
          echo "Current working directory: $(pwd)"
          echo "Contents of GITHUB_WORKSPACE:"
          ls -la $GITHUB_WORKSPACE

      - name: Debug rsync-exclude.txt
        run: |
          echo "GITHUB_WORKSPACE: $GITHUB_WORKSPACE"
          echo "Contents of $GITHUB_WORKSPACE:"
          ls -la $GITHUB_WORKSPACE
          echo "Contents of rsync-exclude.txt:"
          cat $GITHUB_WORKSPACE/rsync-exclude.txt

      - name: Setup PHP with PECL extension
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: grpc, igbinary, memcached

      - name: Validate composer.json
        run: composer validate --no-check-all

      - name: Install composer dependencies
        run: composer install --prefer-dist --no-progress

      - name: Connect to HuchaCash and Deploy
        id: deploy-drupal
        uses: appleboy/ssh-action@v1.2.0
        env:
          GITHUB_WORKSPACE: ${{ github.workspace }}
        with:
          host: ${{ vars.SSH_HOST }}
          key: ${{ secrets.SSH_ED25519_PRIVATE_KEY }}
          username: ${{ vars.SSH_USERNAME }}
          passphrase: 'kabutindi'
          script: |
            echo "Deploying code to server..."

            echo "Passed GITHUB_WORKSPACE: $GITHUB_WORKSPACE"
              ls -la "$GITHUB_WORKSPACE/rsync-exclude.txt"

            # Copy rsync-exclude.txt to the remote server
            scp -v -o StrictHostKeyChecking=no "$GITHUB_WORKSPACE/rsync-exclude.txt" hucha.cash_f48yn987zg5@hucha.cash:/tmp/rsync-exclude.txt

            # Verify file on remote server
            ssh -o StrictHostKeyChecking=no hucha.cash_f48yn987zg5@hucha.cash "ls -la /tmp"

            # Run rsync
            rsync -avzq --no-perms --no-owner --no-group \
            --chown=hucha.cash_f48yn987zg5:psacln \
            --exclude-from="/tmp/rsync-exclude.txt" \
            "$GITHUB_WORKSPACE/" "/var/www/vhosts/hucha.cash/web/"

            echo "Rebuilding Drush cache..."
            vendor/drush/drush/drush cr
