name: Build & Deploy Hucha Backend

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0

      - name: Setup PHP with PECL extension
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: grpc, igbinary, memcached

      - name: Validate composer.json
        run: composer validate --no-check-all

      - name: Install composer dependencies
        run: composer install --prefer-dist --no-progress

      - name: Deploy to Server via Rsync
        uses: Burnett01/rsync-deployments@7.0.1
        with:
          switches: -avzr --exclude-from=./rsync-exclude.txt
          path: ./
          remote_path: /var/www/vhosts/hucha.cash/
          remote_host: ${{ vars.SSH_HOST }}
          remote_user: ${{ vars.SSH_USERNAME }}
          remote_key: ${{ secrets.SSH_ED25519_PRIVATE_KEY }}
          remote_key_pass: ${{ secrets.SSH_ED25519_KEY_PASSPHRASE }}
          rsh: -p 22 #Appends port number on rsync command

      - name: Rebuild cache
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ vars.SSH_HOST }}
          username: ${{ vars.SSH_USERNAME }}
          key: ${{ secrets.SSH_ED25519_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_ED25519_KEY_PASSPHRASE }}
          port: 22
          script: |
            vendor/drush/drush/drush updb
            vendor/drush/drush/drush cim
            vendor/drush/drush/drush updb
            vendor/drush/drush/drush cr
