name: Build & Deploy Hucha Backend

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0

      - name: Connect to server & Deploy
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ vars.SSH_HOST }}
          username: ${{ vars.SSH_USERNAME }}
          key: ${{ secrets.SSH_ED25519_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_ED25519_KEY_PASSPHRASE }}
          port: 22
          script: |
            git fetch
            git reset --hard HEAD
            git merge origin/main
            composer update --no-interaction
            vendor/drush/drush/drush updb
            vendor/drush/drush/drush cim
            vendor/drush/drush/drush updb
            vendor/drush/drush/drush cr
