name: Build & Deploy Hucha Backend

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0

      - name: Setup PHP with PECL extension
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: grpc, igbinary, memcached

      - name: Validate composer.json
        run: composer validate --no-check-all

      - name: Install composer dependencies
        run: composer install --prefer-dist --no-progress

      - name: Deploy to Server via Rsync
        uses: Burnett01/rsync-deployments@7.0.1
        with:
          switches: -avzr --delete
          path: ${{ github.workspace }}/
          remote_path: /var/www/vhosts/hucha.cash/web/
          remote_host: ${{ vars.SSH_HOST }}
          remote_user: ${{ vars.SSH_USERNAME }}
          remote_key: ${{ secrets.SSH_ED25519_PRIVATE_KEY }}
          remote_key_pass: 'kabutindi'
          rsh: -p 22

      - name: Rebuild Drush Cache
        run: |
          ssh -o StrictHostKeyChecking=no -i ${{ secrets.SSH_ED25519_PRIVATE_KEY }} \
          ${{ vars.SSH_USERNAME }}@${{ vars.SSH_HOST }} \
          "cd /var/www/vhosts/hucha.cash/web && vendor/drush/drush/drush cr"

