name: Build & Deploy Hucha Backend

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0

      - name: Setup PHP with PECL extension
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: grpc

      - name: Validate composer.json
        run: composer validate --no-check-all

      - name: Install composer dependencies
        run: composer install --prefer-dist --no-progress

      - name: Connect to HuchaCash and Deploy
        id: deploy-drupal
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ vars.SSH_HOST }}
          key: ${{ secrets.SSH_ED25519_PRIVATE_KEY }}
          username: ${{ vars.SSH_USERNAME }}
          passphrase: 'kabutindi'
          script: |
            echo "Deploying code to server..."
            rsync -avzq --no-perms --no-owner --no-group \
            --chown=hucha.cash_f48yn987zg5:psacln \
            $GITHUB_WORKSPACE/ /var/www/vhosts/hucha.cash/web/
            echo "Rebuilding Drush cache..."
            vendor/drush/drush/drush cr
